FROM golang:1.26-alpine
RUN for i in 1 2 3; do apk add --no-cache gcc musl-dev sqlite-dev git && break || sleep 2; done
RUN go install github.com/air-verse/air@v1.52.2
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
